// ⚠️ Auto-generated by 1947 Admin Panel
// Last update: 2026-10-02T08:42:10.555Z

const WHATSAPP_NUMBER = "918590988090";

window.PRODUCTS_DATA = [
  {
    "id": 1790930516807,
    "folder": "PRODUCT_1790930516807",
    "name": "TESTING",
    "description": "TESTING",
    "price": 1997,
    "oldPrice": 3000,
    "category": "TESTING CATE",
    "image": "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790930516807/1.jpg",
    "images": [
      "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790930516807/1.jpg",
      "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790930516807/2.jpg",
      "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790930516807/3.jpg"
    ],
    "photoCount": 3,
    "date": "2026-10-02T08:42:10.555Z"
  },
  {
    "id": 1790835630067,
    "folder": "PRODUCT_1790835630067",
    "name": "THE clothing 1947 best combo",
    "description": "THE clothing 1947 best combo free COD",
    "price": 999,
    "oldPrice": 2999,
    "category": "Clothing",
    "image": "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790835630067/1.jpg",
    "images": [
      "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790835630067/1.jpg",
      "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790835630067/2.jpg",
      "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790835630067/3.jpg",
      "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790835630067/4.jpg"
    ],
    "photoCount": 4,
    "date": "2026-10-01T06:20:59.551Z"
  },
  {
    "id": 1790835354254,
    "folder": "PRODUCT_1790835354254",
    "name": "THE MAN TEST",
    "description": "THE MAN TEST only for 1993",
    "price": 1993,
    "oldPrice": 2999,
    "category": "Clothing",
    "image": "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790835354254/1.jpg",
    "images": [
      "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790835354254/1.jpg",
      "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790835354254/2.jpg",
      "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790835354254/3.jpg"
    ],
    "photoCount": 3,
    "date": "2026-10-01T06:16:03.978Z"
  }
];

const products = window.PRODUCTS_DATA;
