// Auto-generated by 1947 Admin Panel
// Last update: 2026-10-03T05:14:00.650Z

const WHATSAPP_NUMBER = "918590988090";

window.PRODUCTS_DATA = [
  {
    "id": 1790954082224,
    "folder": "PRODUCT_1790954082224",
    "name": "TEST",
    "description": "TEST",
    "price": 999,
    "oldPrice": 1999,
    "category": "Clothing",
    "image": "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790954082224/1.jpg",
    "images": [
      "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790954082224/1.jpg",
      "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790954082224/2.jpg",
      "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790954082224/3.jpg",
      "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790954082224/4.jpg",
      "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790954082224/5.jpg"
    ],
    "photoCount": 5,
    "date": "2026-10-02T15:15:03.504Z"
  },
  {
    "id": 1790835354254,
    "folder": "PRODUCT_1790835354254",
    "name": "THE MAN TEST",
    "description": "THE MAN TEST only for 1993",
    "price": 1993,
    "oldPrice": 2999,
    "category": "Clothing",
    "image": "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790835354254/1.jpg",
    "images": [
      "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790835354254/1.jpg",
      "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790835354254/2.jpg",
      "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790835354254/3.jpg"
    ],
    "photoCount": 3,
    "date": "2026-10-01T06:16:03.978Z"
  }
];

const products = window.PRODUCTS_DATA;
