// ⚠️ Auto-generated by 1947 Admin Panel
// Last update: 2026-10-01T06:16:03.978Z

const WHATSAPP_NUMBER = "918590988090";

window.PRODUCTS_DATA = [
  {
    "id": 1790835354254,
    "folder": "PRODUCT_1790835354254",
    "name": "THE MAN TEST",
    "description": "THE MAN TEST only for 1993",
    "price": 1993,
    "oldPrice": 2999,
    "category": "Clothing",
    "image": "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790835354254/1.jpg",
    "images": [
      "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790835354254/1.jpg",
      "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790835354254/2.jpg",
      "https://raw.githubusercontent.com/modulosagency-web/1947-Store/main/images/PRODUCT_1790835354254/3.jpg"
    ],
    "photoCount": 3,
    "date": "2026-10-01T06:16:03.978Z"
  }
];

const products = window.PRODUCTS_DATA;
